# Generated by Django 3.1.7 on 2021-04-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210416_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_small',
            field=models.ImageField(blank=True, null=True, upload_to='small_img/'),
        ),
    ]
