# Generated by Django 3.1.7 on 2021-05-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210513_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.FloatField(default=0, verbose_name='Середній рейтинг'),
        ),
        migrations.AddField(
            model_name='product',
            name='votes',
            field=models.FloatField(default=0, verbose_name='Кількість голосів'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desctiption',
            field=models.TextField(verbose_name='Опис товару'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desctiption_ru_ru',
            field=models.TextField(null=True, verbose_name='Опис товару'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desctiption_uk_ua',
            field=models.TextField(null=True, verbose_name='Опис товару'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_small',
            field=models.ImageField(blank=True, null=True, upload_to='small_img/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг'),
        ),
    ]
