# Generated by Django 3.1.7 on 2021-05-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210514_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='Кількість голосів'),
        ),
    ]
