# Generated by Django 3.1.7 on 2021-06-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210622_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_url_2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
