# Generated by Django 3.1.7 on 2021-07-31 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_product_video_url_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf',
            field=models.FileField(blank=True, upload_to='pdf/'),
        ),
    ]
