# Generated by Django 3.1.7 on 2021-08-25 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210825_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textabout',
            old_name='about_us',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='textabout',
            old_name='about_us_ru_ru',
            new_name='about_ru_ru',
        ),
        migrations.RenameField(
            model_name='textabout',
            old_name='about_us_uk_ua',
            new_name='about_uk_ua',
        ),
    ]
